spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # 해당 spring의 driverclassname은 org >> mariadb >> jdbc >> Driver에서 찾을것
    url: jdbc:mariadb://localhost:3306/prototype
    # URL은 jdbc는 mariadb이고, localhost는 3306이고, jdbc내에서 prototype 이라는 db를 잦는다
    username: root
    # 사용자는 root으로 설정하고
    password: green502
    # mariadb의 암호는 green502이다

mybatis:
  mapper-locations: mappers/**/*.xml
#mybatis는 mappers 내에서 모든 xml 파일들을 참조할것

springdoc:
  swagger-ui:
    path: /swagger.html

# springdoc 내에서는 swagger-ui에서 swagger.html을 찾아가도록 할것